<?php
	$image_sizes = array(
		1 => "630x300",
		2 => "550x400",
		3 => "450x420",
		4 => "600x300",
		5 => "550x350",
		6 => "500x420"
	);

	$moments = array(
		array(
			"moments_body" => "On July 1, 2017, Canada celebrates its 150th anniversary since Confederation in 1867, along with all of the daring moments that have defined the country’s past and future.",
			"moments_title" => "150 and beyond.",
			"moments_image_size" => 1,
			"index" => 1,
		),
		array(
			"moments_body" => "In 2017, Canada was ranked the world’s second best country in an annual report from a major U.S. news outlet. In addition, it regularly receives credit for having some of the world’s most “liveable” cities, including Vancouver, Calgary, and Toronto.",
			"moments_title" => "The second best of the best.",
			"moments_image_size" => 2,
			"index" => 2,
		),
		array(
			"moments_body" => "Canada maintains a direct phone line to the federal government that provides general information on Government of Canada programs, services, and initiatives and how to access them. The number is 1-800-O-Canada.",
			"moments_title" => "Call for help.",
			"moments_image_size" => 3,
			"index" => 3,
		),
		array(
			"moments_body" => "Following the Fort McMurray, AB wildfire in 2016, the Canadian Red Cross CEO announced that $165 million had been donated by Canadians to the relief effort. The federal government contributed $104 million to match individual Canadian donors, and the province matched the $30 million given by individual Albertans.",
			"moments_title" => "Giving relief.",
			"moments_image_size" => 4,
			"index" => 4,
		),
		array(
			"moments_body" => "After years of failed research attempts to find the famed HMS Terror, an Inuit Canadian Ranger on patrol spotted the ship’s mast, confirming its location in local legend. He led researchers to the ship in a matter of hours. ",
			"moments_title" => "Searching for sunken Terror.",
			"moments_image_size" => 5,
			"index" => 5,
		),
		array(
			"moments_body" => "Between 2015-2016, the government of Canada played an active role in resettling more than 39,000 Syrian refugees who were displaced due to conflict in their home country.",
			"moments_title" => "Safe harbour.",
			"moments_image_size" => 6,
			"index" => 6,
		),
		array(
			"moments_body" => "Canadian band The Tragically Hip’s homecoming show in Kingston, ON was broadcast nationwide on the CBC following the news of singer Gord Downie’s cancer diagnosis in 2016.",
			"moments_title" => "A show seen coast to coast.",
			"moments_image_size" => 1,
			"index" => 7,
		),
		array(
			"moments_body" => "Canadian novelist Lawrence Hill released his renowned novel The Book of Negroes in 2015. He went on the receive the Order of Canada, and was inducted into Canada’s Walk of Fame.",
			"moments_title" => "Powerful words.",
			"moments_image_size" => 2,
			"index" => 8,
		),
		array(
			"moments_body" => "In December 2015, Canadian artists held seven of the Top 10 Billboard spots. The only other foreign country to do so was the U.K. during the height of Beatlemania in the 1960s.",
			"moments_title" => "Canada makes the hits.",
			"moments_image_size" => 3,
			"index" => 9,
		),
		array(
			"moments_body" => "The newly-elected Canadian Prime Minister appointed the first gender-equal cabinet in Canadian history in 2015. When asked why, he provided a simple response. “Because it’s 2015.”",
			"moments_title" => "“Because it’s 2015.”",
			"moments_image_size" => 4,
			"index" => 10,
		),
		array(
			"moments_body" => "After finishing tenth in the qualifier at the 2014 Olympics, Canadian speed skater Gilmore Junio gave up his spot in the 500m competition to teammate Denny Morrison, who went on to win a silver medal in his place.",
			"moments_title" => "The silver sacrifice.",
			"moments_image_size" => 5,
			"index" => 11,
		),
		array(
			"moments_body" => "At the 2014 Olympics, the Canadian team’s Ski Coach came to the aid of a Russian skier who had broken a ski and was struggling to finish his run. The coach ran onto the course and strapped him into a Canadian athlete’s spare ski. ",
			"moments_title" => "A good sport.",
			"moments_image_size" => 6,
			"index" => 12,
		),
		array(
			"moments_body" => "At a pro hockey game in Toronto during the 2014 season, the national anthem singer’s microphone cut out in the middle of the U.S. national anthem. Without missing a beat, the home town crowd joined together to finish singing the away team’s anthem as a group.",
			"moments_title" => "Oh Canada.",
			"moments_image_size" => 1,
			"index" => 13,
		),
		array(
			"moments_body" => "The world’s best food markets were ranked by a global publication in 2012 with Toronto’s St. Lawrence Market beating out New York’s Union Square Greenmarket and St. Lucia’s Castries Market to take the top spot.",
			"moments_title" => "A marketable difference.",
			"moments_image_size" => 2,
			"index" => 14,
		),
		array(
			"moments_body" => "Montreal’s Arcade Fire shocked the music world by winning the Grammy for Album of the Year in 2011 for their tour de force The Suburbs, beating out several much more famous and commercially successful U.S. acts in the process.",
			"moments_title" => "The music world’s stage.",
			"moments_image_size" => 3,
			"index" => 15,
		),
		array(
			"moments_body" => "Canada won the most gold medals at the 2010 Olympics in Vancouver, finishing with 14 golds, the last of which was a result of the Canadian hockey team’s famous “golden goal” in overtime. No country had won that many golds at home before, and no country has matched the feat since.",
			"moments_title" => "Canada brings home the gold.",
			"moments_image_size" => 4,
			"index" => 16,
		),
		array(
			"moments_body" => "The first Canadian woman inducted into the Hockey Hall of Fame received the honour long after being controversially left off the first women’s Olympics team in 1998.",
			"moments_title" => "Skating a trail.",
			"moments_image_size" => 5,
			"index" => 17,
		),
		array(
			"moments_body" => "When a Canadian freestyle skier won the gold medal in men’s moguls at the 2010 Olympics in Vancouver, he became the first Canadian to win gold at an Olympics held on home soil.",
			"moments_title" => "First gold.",
			"moments_image_size" => 6,
			"index" => 18,
		),
		array(
			"moments_body" => "A young up-and-coming Canadian fashion designer saw his work on the world’s stage, when one of his dresses was worn by the First Lady during the presidential inauguration ceremony in 2009.",
			"moments_title" => "Presidential design.",
			"moments_image_size" => 1,
			"index" => 19,
		),
		array(
			"moments_body" => "A milestone in a long and highly influential career, Canada’s most renowned architect unveiled his striking renovations to Toronto’s now iconic art gallery in 2008.",
			"moments_title" => "Standing out.",
			"moments_image_size" => 2,
			"index" => 20,
		),
		array(
			"moments_body" => "After witnessing thousands of people join together to honour fallen Canadian soldiers on the overpasses of Ontario Highway 401, a university student in Windsor started an online petition to rename a section of it, the “Highway of Heroes.” The name stands to this day.",
			"moments_title" => "Honouring heroes.",
			"moments_image_size" => 3,
			"index" => 21,
		),
		array(
			"moments_body" => "A quick-footed basketball player hailing from Victoria, B.C. became the first Canadian to be named professional basketball’s Most Valuable Player in 2005. He was named MVP again in 2006, and retired with the highest career free throw percentage in pro basketball history.",
			"moments_title" => "The MVP from BC.",
			"moments_image_size" => 4,
			"index" => 22,
		),
		array(
			"moments_body" => "Canada became the first country outside of Europe to nationally legalize same-sex marriage with the enactment of the Civil Marriage Act in 2005.",
			"moments_title" => "Canada declares all love is equal.",
			"moments_image_size" => 5,
			"index" => 23,
		),
		array(
			"moments_body" => "Skate4Cancer was founded by a Canadian skateboarder in 2004 after losing many of his loved ones to cancer. He went on the skate over 8,000 km, the distance from his hometown of Newmarket, ON to Los Angeles, CA. ",
			"moments_title" => "Pushing for change.",
			"moments_image_size" => 6,
			"index" => 24,
		),
		array(
			"moments_body" => "In 2004, French Canadian director Denys Arcand’s Les Invasions Barbares won the Oscar for Best Foreign Film. It became the first Canadian film to ever win in the category. ",
			"moments_title" => "Bringing home the hardware.",
			"moments_image_size" => 1,
			"index" => 25,
		),
		array(
			"moments_body" => "Instead of going for the green, Canada’s famed left-handed golfer laid up on the 15th hole at the 2003 edition of golf’s most prestigious tournament to set himself up for a birdie to tie the leader. He went on to become the first lefty and only Canadian to win one of golf’s four major championships.",
			"moments_title" => "A masterful lay-up.",
			"moments_image_size" => 2,
			"index" => 26,
		),
		array(
			"moments_body" => "In September 2003, two men, one a French-Canadian explorer and adventurer, risked their lives to come to the rescue of four hikers on Baffin Island who had attempted to cross a treacherous river and were overtaken by the current.",
			"moments_title" => "Search and rescue.",
			"moments_image_size" => 3,
			"index" => 27,
		),
		array(
			"moments_body" => "Located on a small organic farm two hours north of Toronto, Eigensenn Farm became the first Canadian restaurant to make the World’s 50 Best restaurants list, coming in at number 9 in 2003. It remains one of only two Canadian restaurants to ever make the list.",
			"moments_title" => "Special chefs.",
			"moments_image_size" => 4,
			"index" => 28,
		),
		array(
			"moments_body" => "In 2003, a benefit concert—in response to an outbreak of SARS in Toronto—colloquially known as “SARSStock” became the largest ticketed outdoor event in Canadian history.",
			"moments_title" => "Record-breaking benefit.",
			"moments_image_size" => 5,
			"index" => 29,
		),
		array(
			"moments_body" => "Dr. Mehran Anvari began to pioneer what has become known as remote-controlled surgery in 2003, which may someday replace the need for doctors to be physically present to carry out procedures. In recent years, Dr. Anvari has been developing another innovation: the use of robotic technology originally designed for the International Space Station as tool to aid in the early diagnosis and treatment of breast cancer.",
			"moments_title" => "Remote surgery.",
			"moments_image_size" => 6,
			"index" => 30,
		),
		array(
			"moments_body" => "Canadian hockey player and team captain Hayley Wickenheiser delivered her famous “flag” quote after leading Canada to Olympic gold in the 2002 Olympics. She served as Canada’s flag bearer at the closing ceremonies.",
			"moments_title" => "Carrying the flag.",
			"moments_image_size" => 1,
			"index" => 31,
		),
		array(
			"moments_body" => "Two brave Canadian pilots flew a small plane from Alberta to Antarctica to rescue a stranded doctor in need of medical treatment. In the process, the pair set a world record for landing and taking off in the cold, with temperatures near -60 ˚C.",
			"moments_title" => "Rescue down under.",
			"moments_image_size" => 2,
			"index" => 32,
		),
		array(
			"moments_body" => "A fearless Canadian woman set eight consecutive records for the same distance as a speed skater, a feat that no one had achieved before or has replicated since. ",
			"moments_title" => "Greatness times eight.",
			"moments_image_size" => 3,
			"index" => 33,
		),
		array(
			"moments_body" => "Moments into his first-ever spacewalk, Canadian astronaut Chris Hadfield couldn’t see. Something got in his eyes and made them water, leaving him essentially blind with no way to clear his vision inside his spacesuit. He pressed on and was able to finally shake the tears from his face and complete his mission to install Canadarm2.",
			"moments_title" => "A space oddity.",
			"moments_image_size" => 4,
			"index" => 34,
		),
		array(
			"moments_body" => "Operation Yellow Ribbon was the name given to the Canadian response to the September 11 attacks, where 238 flights were diverted out of U.S. airspace in into the safety of airports on Canadian soil all across the country.",
			"moments_title" => "Emergency response.",
			"moments_image_size" => 5,
			"index" => 35,
		),
		array(
			"moments_body" => "Canada’s Environmental Protection Act came into effect in 1999, providing a concrete approach for identifying and managing chemical substances in the environment that went unregulated in previous programs.",
			"moments_title" => "Protecting what matters.",
			"moments_image_size" => 6,
			"index" => 36,
		),
		array(
			"moments_body" => "Nunavut became Canada’s third territory in 1999, marking the first major change to the country’s political map since Newfoundland and Labrador joined Canada in 1949.",
			"moments_title" => "Welcome aboard.",
			"moments_image_size" => 1,
			"index" => 37,
		),
		array(
			"moments_body" => "A famed Olympic gold medalist swimmer from Canada came out in 1998, which reportedly caused him to lose a lucrative motivational speaker deal. He went on to become a prominent gay rights advocate in Canada and abroad.",
			"moments_title" => "Advocacy in sport.",
			"moments_image_size" => 2,
			"index" => 38,
		),
		array(
			"moments_body" => "Canadian Shania Twain released her third album, Come On Over, in 1997. It became the best-selling country music album, the best-selling studio album by a female act, and the best-selling album by a Canadian, with over 40 million copies sold worldwide.",
			"moments_title" => "Big country.",
			"moments_image_size" => 3,
			"index" => 39,
		),
		array(
			"moments_body" => "A Team Canada sprinter broke the 100-metre record in at the 1996 Olympics in Atlanta, earning him the title of “World’s Fastest Man.”",
			"moments_title" => "The World’s Fastest Man.",
			"moments_image_size" => 4,
			"index" => 40,
		),
		array(
			"moments_body" => "The first time Canadian athlete Chantal Petitclerc took part in a wheelchair race, she finished last. She went on to win 21 Paralympic medals, including 14 golds, starting in 1996 in Atlanta.",
			"moments_title" => "Last place first.",
			"moments_image_size" => 5,
			"index" => 41,
		),
		array(
			"moments_body" => "Toronto Blue Jays’ icon Joe Carter hit a walk-off home run to win the team’s second consecutive World Series championship in 1993. It was first time in history a time trailing in the ninth inning of a World Series game came back to win with a home run.",
			"moments_title" => "“Touch ‘em all, Joe!”",
			"moments_image_size" => 6,
			"index" => 42,
		),
		array(
			"moments_body" => "Canada’s first female astronaut also became the first neurologist in space in 1992. This high-flying woman went on to serve as NASA’s head of medicine for a decade, and later received the Order of Canada.",
			"moments_title" => "New heights.",
			"moments_image_size" => 1,
			"index" => 43,
		),
		array(
			"moments_body" => "The Canadian rower who was the odds-on favourite prior to the Olympics returned from a severe leg injury suffered during training to capture a bronze medal at the games. For her perseverance, she was named Canada’s flag bearer at the closing ceremonies.",
			"moments_title" => "Against the odds.",
			"moments_image_size" => 2,
			"index" => 44,
		),
		array(
			"moments_body" => "An accomplished Canadian computer scientist who’s made major contributions to numerous software systems is credited as the father of the Java programming language, which was developed in 1991.",
			"moments_title" => "Cracking the code.",
			"moments_image" => 46,
			"moments_image_size" => 4,
			"index" => 45,
		),
		array(
			"moments_body" => "Michie Mee was the first Canadian hip-hop MC to sign to a major American label. Her breakthrough album Jamaican Funk – Canadian Style was released in 1991, pioneering hip-hop in Canada for generations to come.",
			"moments_title" => "Mic drop.",
			"moments_image" => 45,
			"moments_image_size" => 3,
			"index" => 46,
		),
		array(
			"moments_body" => "In 1984, two electrical engineering students at the University of Waterloo founded electronics and computer science company Research in Motion (RIM), which went on to revolutionize communications with the development of the BlackBerry.",
			"moments_title" => "Going wireless.",
			"moments_image_size" => 5,
			"index" => 47,
		),
		array(
			"moments_body" => "An Edmonton-born sailor sacrificed his own medal chances to come to the aid of a capsized boat during the 1988 Olympics. He was awarded the Pierre de Coubertin medal for his sportsmanship, self-sacrifice, and courage.",
			"moments_title" => "A lifesaving sacrifice.",
			"moments_image_size" => 6,
			"index" => 48,
		),
		array(
			"moments_body" => "After his disappointing performance at the Olympics, a Canadian figure skater became the first person to land a quadruple jump in competition at the 1988 World Figure Skating Championships in Budapest, Hungary.",
			"moments_title" => "Fourth time’s the charm.",
			"moments_image_size" => 1,
			"index" => 49,
		),
		array(
			"moments_body" => "The Canadian Multiculturalism Act is passed as a law in 1988, guaranteeing people the right to preserve and share their cultural heritage, as well as the freedom to participate in all aspects of Canadian society. The groundwork for the Act was laid in 1971, when Canada became the first country in the world to adopt an official multiculturalism policy.",
			"moments_title" => "A cultural mosaic.",
			"moments_image_size" => 2,
			"index" => 50,
		),
		array(
			"moments_body" => "Cult Canadian comedy show The Kids in the Hall made its television debut on the CBC in 1988. The show has been credited with influencing many comedians in Canada and around the world over the years. ",
			"moments_title" => "Crushing it.",
			"moments_image_size" => 3,
			"index" => 51,
		),
		array(
			"moments_body" => "The People of Canada received a United Nations award for sheltering world refugees in 1986.",
			"moments_title" => "Giving shelter.",
			"moments_image_size" => 1,
			"index" => 52,
		),
		array(
			"moments_body" => "Famed Canadian author Margaret Atwood’s dystopian classic The Handmaid’s Tale was released in 1985. Since its first publication, the influential novel has never been out of print.",
			"moments_title" => "A timeless vision of the future.",
			"moments_image_size" => 5,
			"index" => 53,
		),
		array(
			"moments_body" => "After an accident at age 15, Rick Hansen became a paraplegic. His Man in Motion World Tour—26-month trek, logging more than 40,000 km through 34 countries on four continents before crossing Canada—raised $26 million for spinal cord research and quality of life initiatives.",
			"moments_title" => "Man in motion.",
			"moments_image_size" => 6,
			"index" => 54,
		),
		array(
			"moments_body" => "Before they sold out stadiums, Guy Laliberté and Gilles Ste-Croix began as a pair of street performers in Baie-Saint-Paul, QC. \"La Fete Foraine de Baie-Saint-Paul\" was their first-ever show under the name Cirque du Soliel.",
			"moments_title" => "The circus made modern.",
			"moments_image_size" => 4,
			"index" => 55,
		),
		array(
			"moments_body" => "The flight crew managed to land what has come to be known as the “Gimli Glider” in 1983: a commercial flight that ran out of fuel halfway through its journey due to a miscalculation. It made an emergency landing at a former air base turned racetrack in Gimli, MB, with no serious injuries to those on board or on the ground.",
			"moments_title" => "Taking control in a crisis.",
			"moments_image_size" => 4,
			"index" => 56,
		),
		array(
			"moments_body" => "The Constitution Act passed and was signed into law in 1982. The formal Act of Parliament granted Canada full political independence from the United Kingdom.",
			"moments_title" => "Fully independent.",
			"moments_image_size" => 6,
			"index" => 57,
		),
		array(
			"moments_body" => "In a career filled with firsts, Bertha Wilson achieved many feats in the legal profession. Most notably, she became the first woman appointed as a Justice of the Supreme Court of Canada in 1982.",
			"moments_title" => "A career of firsts.",
			"moments_image_size" => 1,
			"index" => 58,
		),
		array(
			"moments_body" => "The revolutionary Canadarm’s first flight was with the space shuttle Columbia in 1981. During its 30-year run, the Canadarm established Canada as a global leader in technological innovation and robotics.",
			"moments_title" => "Reaching forward.",
			"moments_image_size" => 5,
			"index" => 59,
		),
		array(
			"moments_body" => "With American bald eagles facing extinction, Canadian scientists in Cape Breton scaled trees to capture baby bald eagles before secretly sending them on a plane full of fish heads to the American east coast. Over 500 eagles were bred thanks to their efforts, and the American bald eagle population went from endangered to unlisted in only 15 years.",
			"moments_title" => "Saved from extinction.",
			"moments_image_size" => 6,
			"index" => 60,
		),
		array(
			"moments_body" => "Canadian Terry Fox began his Marathon of Hope in St. John’s in 1980. He ran for 3,339 miles, nearly a marathon a day, for 143 days, all after having one of his legs amputated due to cancer. Although he was unable to reach his destination, his spirit and example continue to inspire Canadians to this day.",
			"moments_title" => "A big step for hope.",
			"moments_image_size" => 4,
			"index" => 61,
		),
		array(
			"moments_body" => "Two years before there was MTV, there was The New Music. The groundbreaking Citytv program, created by John Martin and originally hosted by Canadians Jeanne Beker and J.D. Roberts, was the first in-depth music show of its kind, exposing local bands and music culture to a TV audience for the first time.",
			"moments_title" => "Making music new.",
			"moments_image_size" => 3,
			"index" => 62,
		),
		array(
			"moments_body" => "Canadian Dr. Phil Nuytten developed the Newtsuit in 1979: a revolutionary one-atmosphere diving suit. His contributions to the field have continued over the years, and he is currently developing a new type ultra-lightweight powered exoskeleton called the Exosuit.",
			"moments_title" => "No pressure.",
			"moments_image_size" => 6,
			"index" => 63,
		),
		array(
			"moments_body" => "Canadians Chris Haney and Scott Abbott weren’t exactly sure how to create a board game, but they knew they had a good idea for one. To turn their idea into reality, they posed as reporters at a Montreal toy fair to get the information they needed. Two years later, their hand-scribbled pieces of paper became Trivial Pursuit.",
			"moments_title" => "Here’s some trivia for you.",
			"moments_image_size" => 1,
			"index" => 64,
		),
		array(
			"moments_body" => "Canada produced one of the most prolific inventors of the twentieth century. This man’s contributions include the electric wheelchair, the micro-surgical staple gun, Canada’s first nuclear reactor, and the famed Canadarm device used in the space shuttle—amongst many others. At age 72, he was summoned out of retirement to help update the Canadarm, due to his unparalleled knowledge of its inner workings.",
			"moments_title" => "Canada’s Renaissance man.",
			"moments_image_size" => 5,
			"index" => 65,
		),
		array(
			"moments_body" => "In 1976, what was then the tallest freestanding structure in the world opened its doors in Toronto. It was eventually overtaken, but it remains the tallest freestanding structure in the Western hemisphere, and a defining part of the city’s skyline.",
			"moments_title" => "A towering achievement.",
			"moments_image" => 67,
			"moments_image_size" => 6,
			"index" => 66,
		),
		array(
			"moments_body" => "Originally called the Festival of Festivals, the first Toronto International Film Festival was held in 1976. Since its inception, the festival has grown into one of the world’s premiere film events.",
			"moments_title" => "Let’s start the show.",
			"moments_image" => 66,
			"moments_image_size" => 4,
			"index" => 67,
		),
		array(
			"moments_body" => "The industrious beaver was officially declared the national animal of Canada in 1975, despite appearing as an unofficial symbol as early as the First World War. Along with the Maple Leaf, it has become a recognizable symbol of pride for Canadians around the world.",
			"moments_title" => "Leave it to the beaver.",
			"moments_image_size" => 3,
			"index" => 68,
		),
		array(
			"moments_body" => "In 1974, Canada took ownership of Santa’s address. The mailing address—Santa Claus, North Pole HOH OHO—is owned by Canada Post. Each year, volunteers reply to the millions of letters sent to Santa, writing back in over 30 languages.",
			"moments_title" => "Santa answers.",
			"moments_image_size" => 6,
			"index" => 69,
		),
		array(
			"moments_body" => "During the infamously heated Canada-Russia hockey Summit Series in 1972, Canadian Paul Henderson scored what has become one of the country’s most iconic and celebrated winning goals of all time.",
			"moments_title" => "The goal heard ‘round the world.",
			"moments_image_size" => 1,
			"index" => 70,
		),
		array(
			"moments_body" => "Canada’s first world championship medalist in downhill skiing was born in Saskatchewan with no mountains to train on. So instead, he strapped into a ski rack atop his Dad’s pickup truck, who then drove him down the highway at speeds up to 100 km/h. This unorthodox training paid off when he skied to victory in 1972.",
			"moments_title" => "From highways to hilltops.",
			"moments_image_size" => 5,
			"index" => 71,
		),
		array(
			"moments_body" => "IMAX theatre technology is developed by Canadians Graeme Ferguson, Roman Kroitor, Robert Kerr, and William C. Shaw in 1970, with the first permanent theatre being unveiled at Ontario Place in Toronto the following year. Today, IMAX theatres are found all over the world.",
			"moments_title" => "Making the big screen bigger.",
			"moments_image_size" => 6,
			"index" => 72,
		),
		array(
			"moments_body" => "Three Canadian scientists and engineers teamed together to do pioneering work in computer music and animation at the National Research Council of Canada in the 1970s that was extremely influential in the field of human-computer interaction.",
			"moments_title" => "Actually, it does compute.",
			"moments_image_size" => 4,
			"index" => 73,
		),
		array(
			"moments_body" => "A Vancouver-based chef is credited with popularizing Japanese cuisine in both Canada and the West Coast, due in part to his influential take on sushi. Noticing that customers were reluctant to try sushi with seaweed visible, he added rice to the outside of the roll, inspiring what has become known as the California Roll worldwide.",
			"moments_title" => "On a roll.",
			"moments_image_size" => 3,
			"index" => 74,
		),
		array(
			"moments_body" => "Medicare, or universal health care, came into effect Canada-wide in 1968, providing universal coverage for all citizens and permanent residents. The view that health care is a social good rather than a commodity has become a defining feature of Canadian society.",
			"moments_title" => "Care for everyone.",
			"moments_image_size" => 6,
			"index" => 75,
		),
		array(
			"moments_body" => "Playing as a six-year-old in a league of 10-year-olds, a young hockey prodigy couldn’t find a jersey that fit. Instead, his tucked his oversized jersey into the back of his hockey pants. He continued to do so throughout his career while breaking nearly every professional hockey record there was.",
			"moments_title" => "Keep your eye on the tuck.",
			"moments_image_size" => 1,
			"index" => 76,
		),
		array(
			"moments_body" => "The Expo 67 World’s Fair opened in Montreal in 1967. It went on to be considered the most successful World's Fair of the 20th Century, and set a single-day attendance record, with 569,500 people in attendance.",
			"moments_title" => "Capturing the world’s imagination.",
			"moments_image_size" => 5,
			"index" => 77,
		),
		array(
			"moments_body" => "In 1967, In The Heat of the Night took home the Oscar for Best Picture. Its director, Canadian Norman Jewison, was also nominated for Best Director.",
			"moments_title" => "The best on the big screen.",
			"moments_image_size" => 6,
			"index" => 78,
		),
		array(
			"moments_body" => "After going 15 rounds against Muhammad Ali at Maple Leaf Gardens in 1966 without so much as getting knocked down, Canadian boxer George Chuvalo was declared the loser of the fight. But his legacy lived on, as Ali later referred to Chuvalo as, “The toughest guy I ever fought.”",
			"moments_title" => "Going toe-to-toe with greatness.",
			"moments_image_size" => 4,
			"index" => 79,
		),
		array(
			"moments_body" => "During the Suez Crisis in 1964, Canadian peacekeepers were not allowed on the ground in Egypt due to the country’s flag still featuring Britain’s Union Jack. Canada’s newly-appointed Prime Minister then ordered that the country create its own flag, and the Maple Leaf was born.",
			"moments_title" => "The Maple Leaf makes its debut.",
			"moments_image_size" => 3,
			"index" => 80,
		),
		array(
			"moments_body" => "In 1964, a defenceman in a pro hockey game broke his leg during a playoff game, and had to be stretchered off of the ice. He later returned to the game for overtime and scored the game-winning goal, helping propel his team to their third consecutive championship.",
			"moments_title" => "Unbreakable effort.",
			"moments_image_size" => 6,
			"index" => 81,
		),
		array(
			"moments_body" => "At the 1964 Olympics in Tokyo, George Hungerford and Roger Jackson were originally the alternates in the rowing competition. Canadian Olympic officials and the media skipped the event, thinking they didn’t have a chance. When they then won Canada’s first Summer Games gold medal since 1956, the pair were affectionately dubbed the “Golden Rejects.”",
			"moments_title" => "The Golden Rejects.",
			"moments_image_size" => 1,
			"index" => 82,
		),
		array(
			"moments_body" => "It was a Canadian-born pathologist doing breakthrough work in cell progression that helped transform cervical cancer from what was then one of the deadliest forms of cancer to a much more treatable form today.",
			"moments_title" => "Conquering the incurable.",
			"moments_image_size" => 5,
			"index" => 83,
		),
		array(
			"moments_body" => "A Greek-Canadian restaurant owner experimented with pizza toppings at his Chatham, ON establishment, where he decided to add pineapple slices to a pizza in 1962. He then added ham simply because he was out of everything else at the time, and Hawaiian pizza was born.",
			"moments_title" => "Getting tired of the same old toppings.",
			"moments_image_size" => 6,
			"index" => 84,
		),
		array(
			"moments_body" => "Two Canadian doctors discovered the existence of transplantable stem cells at the Ontario Cancer Institute in Toronto in 1961—stem cell science was born.",
			"moments_title" => "The birth of a breakthrough.",
			"moments_image_size" => 4,
			"index" => 85,
		),
		array(
			"moments_body" => "A legally blind electrical engineer from Quebec used technology to better see the world. When computers were still in their infancy in the 1960s, he envisioned a new solution for creating braille characters on paper, revolutionizing the formerly long and expensive process. His invention lives on today as braille translation software.",
			"moments_title" => "Thinking in braille.",
			"moments_image_size" => 3,
			"index" => 86,
		),
		array(
			"moments_body" => "The Hawks performed in Canada for the first time behind a then-unknown Ronnie Hawkins in Hamilton, ON in 1958. Soon after, they became Bob Dylan’s backing band, before setting out on their own as simply, “The Band.”",
			"moments_title" => "Before the band was The Band.",
			"moments_image_size" => 6,
			"index" => 87,
		),
		array(
			"moments_body" => "The first-ever Instant Replay was created with the use of a kinescope by a television producer during a broadcast of CBC’s Hockey Night in Canada in 1955. Its use has since spread to nearly every sport on the planet.",
			"moments_title" => "Let’s take another look.",
			"moments_image_size" => 1,
			"index" => 88,
		),
		array(
			"moments_body" => "In 1954, Canadian Marilyn Bell became the first person to swim across Lake Ontario: a 20-hour swim that stretched over 50 km. Bell endured cold, 21°C water with waves up to five-metres, and even occasional bites from lamprey eels on her arms and legs.",
			"moments_title" => "Diving headfirst into history.",
			"moments_image_size" => 5,
			"index" => 89,
		),
		array(
			"moments_body" => "Long before her illustrious music career, a young Joni Mitchell was hospitalized from polio in her home town in Alberta. After spending several weeks in hospital, she came to accept that her athletic aspirations may have come to an end, and found solace in the arts by teaching herself to play guitar.",
			"moments_title" => "A tough choice.",
			"moments_image_size" => 6,
			"index" => 90,
		),
		array(
			"moments_body" => "In 1952, visionary National Film Board of Canada filmmaker Norman McLaren won an Oscar for his short film, “Neighbours”. The film uses techniques typically reserved for animation to tell the story of escalating animosity between two neighbours over a flower—a subversive commentary on war.",
			"moments_title" => "A revolution in film.",
			"moments_image_size" => 4,
			"index" => 91,
		),
		array(
			"moments_body" => "Mavis Gallant’s first short story, \"Madeline's Birthday\", appeared in the September 1, 1951 issue of The New Yorker. An expat who spent most of her life in Paris, Gallant is an often-overlooked figure in Canadian literature, despite being beloved by Canadian authors, many of whom regard her collected stories as one of Canada’s greatest literary contributions.",
			"moments_title" => "Sold short.",
			"moments_image_size" => 3,
			"index" => 92,
		),
		array(
			"moments_body" => "In 1950, the pacemaker was invented by a doctor at a university in Toronto. In recognition of this doctor’s numerous contributions to the field, he became known as the “Father of biomedical engineering in Canada.”",
			"moments_title" => "Heart breakthrough.",
			"moments_image_size" => 6,
			"index" => 93,
		),
		array(
			"moments_body" => "In 1946, a Black businesswoman from Halifax was arrested for sitting in the \"White-only\" section of a New Glasgow theatre. The woman sued the theatre, and her case became an important tipping point for the modern civil rights movement in Canada.",
			"moments_title" => "The Canadian civil rights movement.",
			"moments_image_size" => 1,
			"index" => 94,
		),
		array(
			"moments_body" => "After enduring years of childhood bullying due to losing his arm in an accident, a man from New Brunswick later wrote the first draft of the Universal Declaration of Human Rights, citing the empathy he gained for all people during his childhood as inspiration.",
			"moments_title" => "Human rights for all.",
			"moments_image_size" => 6,
			"index" => 95,
		),
		array(
			"moments_body" => "During the “Little World Series” in 1946, the hometown Montreal crowd chanted “We Want Jackie!”, embracing the soon-to-be star Montreal Royals infielder Jackie Robinson. They won the series, and Robinson went on the break professional baseball’s colour barrier as a member of the Brooklyn Dodgers.",
			"moments_title" => "“We Want Jackie!”",
			"moments_image_size" => 5,
			"index" => 96,
		),
		array(
			"moments_body" => "Following the Second World War in 1945, Canada was among the founding members of the United Nations. In the years since its inception, Canada has played an integral role as a peacekeeper during numerous conflicts around the world.",
			"moments_title" => "United for peace.",
			"moments_image_size" => 6,
			"index" => 97,
		),
		array(
			"moments_body" => "While living in the Netherlands during World War II, a Canadian actress used her home to hide Allied soldiers from German forces. She was caught and sentenced to hard labour in a German prison camp, where she served four years before escaping and hiking over 125 km to safety.",
			"moments_title" => "Escaping the odds.",
			"moments_image_size" => 4,
			"index" => 98,
		),
		array(
			"moments_body" => "During the Second World War, the Canadian landings on the Juno Beach sector of the Normandy coast became one of the most successful operations carried out on D-Day on June 6, 1944.",
			"moments_title" => "Juno Beach.",
			"moments_image_size" => 3,
			"index" => 99,
		),
		array(
			"moments_body" => "A famed right winger on Montreal’s hockey team spent eight hours moving his family from one end of the city to the other in 1944. The 23-year-old went on to score 8 points in a 9-1 rout that very evening, which became one of many the contributing factors to his status as one of hockey’s legends.",
			"moments_title" => "Moving mountains.",
			"moments_image_size" => 3,
			"index" => 100,
		),
		array(
			"moments_body" => "An exiled Dutch Princess gave birth to her daughter while living in Ottawa, ON. Her hospital room was temporarily declared extraterritorial by the Government of Canada to ensure the princess would be born with purely Dutch lineage. Five years later, the family returned to Canada, bringing 100,000 tulip bulbs with them. Each year, the Dutch continue to send Canada tulips as a thank-you.",
			"moments_title" => "A lasting gesture.",
			"moments_image_size" => 2,
			"index" => 101,
		),
		array(
			"moments_body" => "The first Canadian woman to direct a colour film was Judith Crawley in 1940. Instrumental to the development of filmmaking in Canada, Crawley went on to be regarded as Canada’s first female filmmaker.",
			"moments_title" => "Breaking through black-and-white.",
			"moments_image_size" => 1,
			"index" => 102,
		),
		array(
			"moments_body" => "The anti-gravity suit was devised and prototyped by a Canadian man in 1940. When he first tested it, he quickly realized he had designed the suit to fit to him while he was standing, not sitting in an airplane. He described the experience as feeling as though the pressure was going to cut him in two. His G-Suit is credited with having saved the lives of thousands of Allied fighter pilots during the war.",
			"moments_title" => "Suiting up.",
			"moments_image_size" => 6,
			"index" => 103,
		),
		array(
			"moments_body" => "The first steps forward in mobile wireless communication were taken by a pioneering Canadian man. He created and patented many communications devices, the most influential of which was an early version of the walkie-talkie in 1938.",
			"moments_title" => "Walkie-Talkie man.",
			"moments_image_size" => 5,
			"index" => 104,
		),
		array(
			"moments_body" => "The Canadian Broadcasting Corporation went on air for the first time in 1936. It has had a tremendous amount of influence over the development of Canadian journalism and entertainment in radio, television, and other forms of media since its inception.",
			"moments_title" => "We’re on the air.",
			"moments_image_size" => 4,
			"index" => 105,
		),
		array(
			"moments_body" => "A French-Canadian man built the first snowmobile in 1935, a vehicle steered by skis that could hold two or three passengers. Two years later, the same man built the seven-seat B7, which quickly sold to doctors, ambulance drivers, and priests living in remote areas, before the invention quickly expanded into widespread commercial and public use.",
			"moments_title" => "Snow man.",
			"moments_image_size" => 3,
			"index" => 106,
		),
		array(
			"moments_body" => "After receiving numerous rejections, legend has it that Joe Shuster threw one of his early comic book ideas into his fireplace out of frustration, causing his co-author Jerry Siegel jump up and quickly save the cover from the flames. As we now know, fire can’t harm Superman",
			"moments_title" => "Before he could save others, he needed to be saved.",
			"moments_image_size" => 2,
			"index" => 107,
		),
		array(
			"moments_body" => "Canadian Emily Carr was one of the first artists to attempt to capture the spirit of Canada in a modern style. Previously, Canadian paintings had been mostly portraits and representational landscapes. Her work became so influential that one of her early 1930s works, The Crazy Stair (The Crooked Staircase), sold for $3.39 million at auction in 2013.",
			"moments_title" => "Modern art.",
			"moments_image_size" => 1,
			"index" => 108,
		),
		array(
			"moments_body" => "In 1931, the Statute of Westminster granted Canada near-complete political independence from Britain, including the right to an independent foreign policy. The Statute was a major step in Canada forming an identity of its own.",
			"moments_title" => "Independent at last.",
			"moments_image_size" => 6,
			"index" => 109,
		),
		array(
			"moments_body" => "Three doctors from the Hospital for Sick Children in Toronto developed and produced Pablum in 1930: a cereal-like food made of vitamins, minerals, and starches designed to improve infant nutrition. The product was incredibly popular when it debuted, and its royalties helped support the hospital’s research initiatives for the next 25 years.",
			"moments_title" => "Research and development.",
			"moments_image_size" => 5,
			"index" => 110,
		),
		array(
			"moments_body" => "Canada’s bravest pilot in the First World War was a flying ace who eventually received the Victoria Cross during the First World War. The pilot was credited with 72 official victories, making him the top Canadian ace of the war. ",
			"moments_title" => "Canada’s ace.",
			"moments_image_size" => 4,
			"index" => 111,
		),
		array(
			"moments_body" => "After her numerous roles during the silent film era made her one of the most popular actresses of her time, Canadian Mary Pickford starred in her first talkie, Coquette, in 1929. Her role in the film won her the second-ever Oscar for Best Actress.",
			"moments_title" => "Star power.",
			"moments_image_size" => 3,
			"index" => 112,
		),
		array(
			"moments_body" => "In 1928, Canada’s first female broadcaster made her on-air debut. Her casual, “guest-in-your-living room” approach made her extremely popular across the country, earning her the nickname, the “Queen of the Airwaves.”",
			"moments_title" => "Heard from coast to coast.",
			"moments_image_size" => 2,
			"index" => 113,
		),
		array(
			"moments_body" => "Leslie McFarlane was a largely unknown Canadian author who wrote the majority of the immensely popular Hardy Boys book series from 1927-1946, penning 19 of the first 25 books without receiving credit until many years later. To this day, all Hardy Boys books are written under the same penname: Franklin W. Dixon.",
			"moments_title" => "The mystery author.",
			"moments_image_size" => 1,
			"index" => 114,
		),
		array(
			"moments_body" => "Canadian soldier Harry Colebourn bought an orphaned bear cub in England during the First World War and named her after his home town of Winnipeg. The bear inspired author A.A. Milne to create one of the world’s most famous and beloved children’s book characters, Winnie the Pooh.",
			"moments_title" => "One sweet story.",
			"moments_image_size" => 6,
			"index" => 115,
		),
		array(
			"moments_body" => "Long before finding its place on the dime, the legendary Bluenose schooner launched in Nova Scotia in 1922. The Bluenose had a long career as both a fishing and racing schooner, winning several International Fishermen’s Trophies—in many cases, by beating ships that were specifically designed to beat the Bluenose. ",
			"moments_title" => "Turning on a dime.",
			"moments_image_size" => 5,
			"index" => 116,
		),
		array(
			"moments_body" => "Agnes MacPhail became the first and only woman elected to the House of Commons in 1921, the first year that women had the vote. MacPhail went on to become a champion of prison reform, advocating for education and rehabilitation over corporal punishment, becoming one of the first prominent Canadian figures to do so.",
			"moments_title" => "An important appointment.",
			"moments_image_size" => 4,
			"index" => 117,
		),
		array(
			"moments_body" => "Dr. Frederick Banting reportedly chose his summer lab assistant with a flip of a coin in 1921, when Charles Best won over Clark Noble. That very summer, Banting and Best’s research led to the pair discovering and developing insulin as a treatment for diabetes.",
			"moments_title" => "One critical coin toss.",
			"moments_image_size" => 3,
			"index" => 118,
		),
		array(
			"moments_body" => "Self-described modern artists the Group of Seven held their first exhibit in Toronto in 1920. They interpreted and transformed the Canadian landscape with new techniques and a use of vivid colour, leading to the Group becoming the among the most influential artists in country’s history.",
			"moments_title" => "Changing the landscape.",
			"moments_image_size" => 2,
			"index" => 119,
		),
		array(
			"moments_body" => "A group of Icelandic Canadians formed a pro hockey team that wasn’t accepted by other teams due to their nationality. They fought as a unit in the First World War, and lost two members. They then went on to represent Canada at the Olympics, and won the first-ever gold medal in Olympic Ice Hockey.",
			"moments_title" => "Scoring the first gold.",
			"moments_image_size" => 1,
			"index" => 120,
		),
		array(
			"moments_body" => "Royal Canadian Mounted Police hero Sam Steele was so admired that his funeral procession caused a temporary halt to the Winnipeg General Strike as the workers paused to pay their respects to the late officer.",
			"moments_title" => "Paying respect.",
			"moments_image_size" => 6,
			"index" => 121,
		),
		array(
			"moments_body" => "During the First World War, Canada’s role in the Battle of Vimy Ridge became one the country’s most celebrated military victories. ",
			"moments_title" => "Vimy Ridge.",
			"moments_image_size" => 5,
			"index" => 122,
		),
		array(
			"moments_body" => "A woman in Edmonton was appointed the city’s police magistrate in 1916, becoming the first female magistrate in the British Empire. The same woman was later instrumental in the “Persons” case which allowed women to be viewed as “persons” under British law, deeming them eligible to serve in the senate.",
			"moments_title" => "Equality for all “persons.”",
			"moments_image_size" => 4,
			"index" => 123,
		),
		array(
			"moments_body" => "In 1916, women win the right to vote in Manitoba, Saskatchewan, and Alberta. It set a precedent that lead to the 1919 ruling that granted all women over the age of 21 the right to vote in the federal election. ",
			"moments_title" => "Every vote counts.",
			"moments_image_size" => 3,
			"index" => 124,
		),
		array(
			"moments_body" => "Canadian Lieutenant Colonel John McCrae is believed to have written his poem, “In Flanders Fields,” during a bumpy ambulance ride through Essex Farm in Ypres, Belgium. The poppies grew throughout the battlefields and cemeteries of Flanders, and have come to symbolize the memory of the soldiers who have scarified their lives for the country’s freedom.",
			"moments_title" => "His words will never be forgotten.",
			"moments_image_size" => 2,
			"index" => 125,
		),
		array(
			"moments_body" => "Canada joined the First World War in 1914, fighting for first time as an independent unit. With a regular army of only 3110, thousands of young Canadians enlisted in the following weeks. Two months later, the largest convoy to ever cross the Atlantic was on its way to England.",
			"moments_title" => "Answering the call.",
			"moments_image_size" => 1,
			"index" => 126,
		),
		array(
			"moments_body" => "After hearing an argument between a hotelier and a deliveryman over broken eggs, an astute Canadian newspaper editor got to work on an invention that would eliminate the need to literally put all of your eggs in one basket. The egg carton was born, and millions have been produced in the years since.",
			"moments_title" => "There’s got to be a better way.",
			"moments_image_size" => 6,
			"index" => 127,
		),
		array(
			"moments_body" => "It was a pioneering Canadian aviator who became the first person in the British Empire to fly an airplane. Taking off from the ice in his plane, he travelled roughly 10 metres above the ground for almost a kilometre in Baddeck, NS.",
			"moments_title" => "First in flight.",
			"moments_image_size" => 5,
			"index" => 128,
		),
		array(
			"moments_body" => "The famed children’s novel Anne of Green Gables was published in 1908. The story, based on life in Prince Edward Island, has since sold more than 50 million copies and has been translated into 36 languages.",
			"moments_title" => "An Island icon.",
			"moments_image_size" => 4,
			"index" => 129,
		),
		array(
			"moments_body" => "In 1908, Canada began minting its own currency—the first piece being a gold sovereign with a \"C\" for Canada—ending its need to import currency from England. Soon after, the mint started producing the first uniquely Canadian gold coins, featuring the word \"Canada\" and the country's coat of arms.",
			"moments_title" => "Show me the money.",
			"moments_image_size" => 3,
			"index" => 130,
		),
		array(
			"moments_body" => "With a 1907 population of around 4,000 people, Kenora, ON became the smallest town to ever win the Stanley Cup when the Kenora Thistles beat the Montreal Wanderers over a two-game series. Prior to the formation of the National Hockey League, the Wanderers were regarded as one of the most successful hockey teams in history.",
			"moments_title" => "To the last Thistle.",
			"moments_image_size" => 2,
			"index" => 131,
		),
		array(
			"moments_body" => "It was a Canadian-born inventor who developed the idea for the radio, though he rarely gets the credit. His belief that radios worked via continuous waves was opposed by the Italian radio pioneer who insisted on his own “whiplash” theory at the time. The Canadian man’s theory was proven correct a decade later, accelerating the growth of radio technology.",
			"moments_title" => "Making waves.",
			"moments_image_size" => 1,
			"index" => 132,
		),
		array(
			"moments_body" => "During a demonstration on a Montreal street, salesmen P.L. Robertson had a spring-loaded screwdriver slip into his hand, cutting him badly. He decided he needed a safer screw. Soon after, he filed his patent for a square-headed “Robertson” screw and screwdriver, which remain a favourite among builders and engineers today.",
			"moments_title" => "Driving the point home.",
			"moments_image_size" => 6,
			"index" => 133,
		),
		array(
			"moments_body" => "In 1906, a Norwegian sailor, travelling west of King William Island in what is now Nunavut, saw an American whaling ship that had come from San Francisco, CA. At that moment, he realized that he had achieved the elusive Northwest Passage in Canadian waters: a feat that explorers had obsessed over for nearly 400 years.",
			"moments_title" => "North by Northwest.",
			"moments_image_size" => 5,
			"index" => 134,
		),
		array(
			"moments_body" => "In 1904, the Canadian Women’s Press Club was founded by Margaret Graham while travelling in a Canadian Pacific Railway Pullman car between Montreal and St. Louis. The club paved the way for female journalists for over a century before being disbanded in the early 2000s.",
			"moments_title" => "Writing wrongs.",
			"moments_image_size" => 4,
			"index" => 135,
		),
		array(
			"moments_body" => "Canada got its first female nuclear physicist in 1901, a woman who had just received her Master’s degree. At the height of her career, she was considered one of the leading figures in her field.",
			"moments_title" => "Pioneering nuclear physics.",
			"moments_image_size" => 3,
			"index" => 136,
		),
		array(
			"moments_body" => "In 1895, a 51-year-old Canadian sailor set out on a tiny sailboat and travelled the world solo. He became the first person to circumnavigate the earth on a sailboat, a feat of over 74,000 km. He’s now seen as the patron saint of small-boat voyagers, navigators, and adventurers to this day.",
			"moments_title" => "Around the world in 1895.",
			"moments_image_size" => 2,
			"index" => 137,
		),
		array(
			"moments_body" => "After being stuck with a restless physical education class during a long New England winter, Canadian James Naismith set out to invent a new indoor activity to keep his students occupied. After cutting the bottoms out of a pair of peach baskets, the game of basketball was born.",
			"moments_title" => "They saw baskets. He saw hoops.",
			"moments_image_size" => 1,
			"index" => 138,
		),
		array(
			"moments_body" => "In 1885, the rail director of the Canadian Pacific Railway drove the ceremonial last spike into the tracks, which connected Montreal all the way to Port Moody, BC. It became a catalyst for the country’s growth and development, and remains in use to this day.",
			"moments_title" => "A country connected.",
			"moments_image_size" => 6,
			"index" => 139,
		),
		array(
			"moments_body" => "A Canadian chemist was the first person to patent “peanut paste,” a source of nutrition for patients who couldn’t chew well due to cleft palates in 1884. It’s now known worldwide as peanut butter.",
			"moments_title" => "Health nut.",
			"moments_image_size" => 5,
			"index" => 140,
		),
		array(
			"moments_body" => "After a Canadian baseball player broke two of his fingers fielding a ball, he decided to stitch padding into a driving glove instead of missing games. In the process, he popularized what became the modern baseball glove, which is worn by all players today.",
			"moments_title" => "Playing through the pain.",
			"moments_image_size" => 4,
			"index" => 141,
		),
		array(
			"moments_body" => "Toronto’s first Black postal carrier started on the job in 1882. On his first day of work, other workers refused to show him his routes due to the colour of his skin. He persevered, and became a well-respected figure in his community, paving the way for those who followed.",
			"moments_title" => "Braving more than bad weather.",
			"moments_image_size" => 3,
			"index" => 142,
		),
		array(
			"moments_body" => "The same man responsible for Canada's first postage stamp was also known for his work engineering the Intercolonial Railway and the Canadian Pacific Railway. But his most influential contribution to our country, and the world, was his proposal of worldwide standard time zones in 1879.",
			"moments_title" => "A matter of time.",
			"moments_image_size" => 2,
			"index" => 143,
		),
		array(
			"moments_body" => "The Toronto Women’s Literary Club was founded in 1877 by Emily Stowe, a doctor and women’s rights leader. The name shielded the club’s actual purpose: advocating for voting rights for women.",
			"moments_title" => "Suffragette city.",
			"moments_image_size" => 1,
			"index" => 144,
		),
		array(
			"moments_body" => "In 1876, the first telephone call between separate buildings was made from Mount Pleasant, ON to Brantford, ON. To say it was the first of many personal phone calls made by people would be a slight understatement.",
			"moments_title" => "Hello over there.",
			"moments_image_size" => 6,
			"index" => 145,
		),
		array(
			"moments_body" => "The first organized, official indoor hockey game was played in 1875 in Montreal. A flat wooden puck was used instead of a lacrosse ball to prevent injuries to spectators, a decision that shaped one of the key aspects of the game into what it is today.",
			"moments_title" => "Drop the (wooden) puck.",
			"moments_image_size" => 5,
			"index" => 146,
		),
		array(
			"moments_body" => "Medical student Henry Woodward and his partner Matthew Evans built the first-ever incandescent light bulb. After trying and failing to get it off the ground, they sold their patent five years later. To a man named Thomas Edison.",
			"moments_title" => "Let there be light.",
			"moments_image_size" => 4,
			"index" => 147,
		),
		array(
			"moments_body" => "Unlike her Victorian contemporaries, businesswoman and philanthropist Luce Cuvillier never married. She was also known to smoke cigars, and wear long pants in her garden. What we may never know is full extent of her influence over the politics of longtime companion and Father of Confederation George-Étienne Cartier.",
			"moments_title" => "An unconventional influence.",
			"moments_image_size" => 3,
			"index" => 148,
		),
		array(
			"moments_body" => "Canada’s first-ever automobile was built by a man from Quebec in 1867. The steam-powered car promptly broke down the first time it was showcased it in public. One year later, the refined invention ran smoothly in front of a large crowd at the Stanstead Fair.",
			"moments_title" => "Start your steam engines.",
			"moments_image_size" => 2,
			"index" => 149,
		),
		array(
			"moments_body" => "Ontario, Quebec, Nova Scotia, and New Brunswick unite to form the federal Dominion of Canada on July 1, 1867.",
			"moments_title" => "A country is born.",
			"moments_image_size" => 1,
			"index" => 150,
		)
	);

	$default_image_folder = "/wp-content/uploads/1/2017/05/";
	foreach($moments as $key => $value) {
		if (array_key_exists('moments_image', $value) == false) {
			$moments[$key]['moments_image'] = $default_image_folder . strval($key + 1) . '.jpg';
		} else {
			$moments[$key]['moments_image'] = $default_image_folder . strval($moments[$key]['moments_image']) . '.jpg';
		}
	}
?>